Expose unread and download count of Manga in category api
Suwayomi/Suwayomi-Server pull request #227
Opened 2021-10-24 21:10 UTC by mrsOwlex

Implements unread and download counters for Mangas in Libraries Closes #224

extended /api/v1/category/{categoryId} to return the MangaViewDataClass.
This I mapped by MangaView which is a sql-view.

Feature of it are the download_count and unread_count

As previous discussions were talking about performance I included a basic test, so we can switch around to a different solution in the future.

2021-10-24 21:21 UTC, AriaMoradi requested changes

2021-10-24 21:21 UTC, AriaMoradi commented on server/src/main/kotlin/suwayomi/tachidesk/manga/model/dataclass/MangaDataClass.kt
> + *
hmm, fix please.

2021-10-24 21:28 UTC, AriaMoradi requested changes

2021-10-24 21:28 UTC, AriaMoradi commented on server/src/main/kotlin/suwayomi/tachidesk/manga/model/view/MangaView.kt
> + */
I'm not really a fan of introducing Views to the codebase specially when the ORM doesn't support them. It's a neat trick and works for this case, but the solution is likely to be reused in the future and I don't want it to spread.

Sorry, we have to make due with simple queries.

2021-10-25 08:07 UTC, mrsOwlex commented on server/src/main/kotlin/suwayomi/tachidesk/manga/model/view/MangaView.kt
> + */
Fine. I'll create it as a query then. Shouldn't be that hard now that I have a test 😋

If we would implement filters on the API I'd recommend revisiting this solution as it is much more straightforward.

2021-10-25 10:02 UTC, mrsOwlex commented on server/src/main/kotlin/suwayomi/tachidesk/manga/model/view/MangaView.kt
> + */
Implemented it now i a fully supported way. Ready for a new review

2021-10-25 10:11 UTC, AriaMoradi commented
I may do some cleanup afterwards

2021-10-25 10:11 UTC, merged