WIP Api Documentation
Suwayomi/Suwayomi-Server pull request #248
Opened 2021-11-10 21:10 UTC by ntbm

2021-11-11 20:52 UTC, AriaMoradi requested changes

2021-11-11 20:52 UTC, AriaMoradi commented on server/build.gradle.kts
> +    implementation("io.javalin:javalin-openapi:4.1.1")
Put this with the other javalin packages

2021-11-11 20:52 UTC, AriaMoradi commented on server/src/main/kotlin/suwayomi/tachidesk/manga/controller/UpdateController.kt
> +        ctx.json(updater.getStatus().value.getSummary())
don't make the json yourself, `ctx.result` will automatically convert to json when you give a non-string/non-stream object.

2021-11-12 06:53 UTC, ntbm commented
Continued in #249

2021-11-12 10:34 UTC, closed without merging