Remove support for Sorayomi web interface
Suwayomi/Suwayomi-Server pull request #414
Opened 2022-10-06 15:37 UTC by marcoebbinghaus

fixes #392

2022-10-06 15:38 UTC, marcoebbinghaus commented
Please let me know if I missed something / if the ticket https://github.com/Suwayomi/Tachidesk-Server/issues/392 was meant to have a larger scope.

2022-10-06 19:41 UTC, AriaMoradi requested changes
I didn't look at the rest of the code, You basically just need to reverse #342

2022-10-06 19:41 UTC, AriaMoradi commented on README.md
> -- [Tachidesk-Sorayomi](https://github.com/Suwayomi/Tachidesk-Sorayomi): A Flutter front-end for Desktop(Linux, windows, etc.), Web and Android. UI and UX similar to Tachiyomi.
Doesn't need to be removed

2022-10-07 15:28 UTC, marcoebbinghaus commented
> I didn't look at the rest of the code, You basically just need to reverse #342

I looked through the changes from #342 and imo my commit reverses the relevant changes from there. I also undid the change in README.md as you commented.

Let me know if further alignments are needed.

2022-10-07 15:48 UTC, Syer10 approved these changes

2022-10-07 18:56 UTC, merged