Feature/move server frontend mapping to the frontend
Suwayomi/Suwayomi-Server pull request #591
Opened 2023-07-01 23:02 UTC by schroda

This way, the latest webUI version, which is compatible with the current server version, can be used without the need of a server release

2023-07-16 15:59 UTC, Syer10 requested changes

2023-07-16 15:59 UTC, Syer10 commented on server/src/main/kotlin/suwayomi/tachidesk/server/util/WebInterfaceManager.kt
> +        ZipFile(zipFilePath).extractAll(targetPath)
I think this is a Closable, so I believe the code should be
```suggestion
        ZipFile(zipFilePath).use { it.extractAll(targetPath) }
```

2023-07-20 21:49 UTC, Syer10 approved these changes
@schroda Is this ready to be merged? WebUI has the mapping?

2023-07-20 22:16 UTC, schroda commented
> @schroda Is this ready to be merged? WebUI has the mapping?

not yet, I'll ping you when it's ready

---

I updated the automated webUI update check to use the "HAScheduler"

2023-07-21 00:40 UTC, schroda commented
I added a function to get the latest version of the webUI preview, instead of having to change the naming pattern of the bundled webUI zip file from `Tachidesk-WebUI-<revision>.zip` to `Tachidesk-WebUI.zip`

2023-07-21 00:46 UTC, schroda commented
webUI repo is up-to-date

2023-07-21 00:48 UTC, merged