Add mutation to clear the cached images
Suwayomi/Suwayomi-Server pull request #775
Opened 2023-11-19 10:57 UTC by schroda

2023-11-20 00:20 UTC, Syer10 requested changes

2023-11-20 00:20 UTC, Syer10 commented on server/src/main/kotlin/suwayomi/tachidesk/graphql/mutations/ImageMutation.kt
> +    data class ClearCachedImagesInput(
Needs clientMutationId

2023-11-20 20:45 UTC, schroda commented on server/src/main/kotlin/suwayomi/tachidesk/graphql/mutations/ImageMutation.kt
> +    data class ClearCachedImagesInput(
fixed

2023-11-25 16:53 UTC, Syer10 approved these changes

2023-11-25 16:53 UTC, merged